/*
 * This file was automatically generated by EvoSuite
 * Sat Jan 18 19:41:32 GMT 2020
 */


import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.LinkedList;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class CarroEletrico_ESTest extends CarroEletrico_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Coordinate coordinate0 = new Coordinate(70.0, 3796);
      LinkedList<ParDatas> linkedList0 = new LinkedList<ParDatas>();
      CarroEletrico carroEletrico0 = new CarroEletrico("", "", "Ll{r", 3796, (-1.0), 3796, 3796, coordinate0, true, (-1), linkedList0);
      CarroEletrico carroEletrico1 = carroEletrico0.clone();
      assertEquals(3796, carroEletrico1.getAutonomia());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      CarroEletrico carroEletrico0 = new CarroEletrico();
      carroEletrico0.setClassificacao(1);
      CarroEletrico carroEletrico1 = carroEletrico0.clone();
      assertEquals(0, carroEletrico1.getAutonomia());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      CarroEletrico carroEletrico0 = new CarroEletrico();
      CarroEletrico carroEletrico1 = carroEletrico0.clone();
      assertEquals(0.0, carroEletrico1.getPreco(), 0.01);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Coordinate coordinate0 = new Coordinate(2353, 2353);
      CarroEletrico carroEletrico0 = new CarroEletrico();
      List<ParDatas> list0 = carroEletrico0.getDatasAlugueres();
      CarroEletrico carroEletrico1 = new CarroEletrico("Eb", "CarroEletrico", "Autonomia: ", 2353, 2353, 0.0, 4197, coordinate0, false, (-3021), list0);
      CarroEletrico carroEletrico2 = carroEletrico1.clone();
      assertEquals(0.0, carroEletrico2.getConsumo(), 0.01);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      CarroEletrico carroEletrico0 = new CarroEletrico();
      List<ParDatas> list0 = carroEletrico0.getDatasAlugueres();
      CarroEletrico carroEletrico1 = new CarroEletrico((String) null, "CarroEletrico", "", 0, 0, 0, 0, (Coordinate) null, false, (-66), list0);
      // Undeclared exception!
      try { 
        carroEletrico1.toString();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Veiculo", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Coordinate coordinate0 = new Coordinate((-86), 0.0);
      CarroEletrico carroEletrico0 = null;
      try {
        carroEletrico0 = new CarroEletrico("6@7`", "6@7`", "Coordinate", 0, (-628.4), 0, (-86), coordinate0, false, (-86), (List<ParDatas>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Veiculo", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      CarroEletrico carroEletrico0 = null;
      try {
        carroEletrico0 = new CarroEletrico((CarroEletrico) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Veiculo", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      CarroEletrico carroEletrico0 = new CarroEletrico();
      boolean boolean0 = carroEletrico0.equals("***** Carro El\u00E9trico *****\n*****    VE\u00CDCULO    *****\nMarca: \nMatr\u00EDcula: \nNIF do Propriet\u00E1rio: \nVelocidade M\u00E9dia: 0\nPre\u00E7o Base por Km: 0.0\nConsumo: 0.0\nAutonomia: 0\nPosi\u00E7\u00E3o (latitude e longitude): 0, 0\nDispon\u00EDvel: false\nClassifica\u00E7\u00E3o: 0\n");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      CarroEletrico carroEletrico0 = new CarroEletrico();
      boolean boolean0 = carroEletrico0.equals(carroEletrico0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      CarroEletrico carroEletrico0 = new CarroEletrico();
      boolean boolean0 = carroEletrico0.equals((Object) null);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      LinkedList<ParDatas> linkedList0 = new LinkedList<ParDatas>();
      CarroEletrico carroEletrico0 = new CarroEletrico("CarroElettrico", "CarroElettrico", "CarroElettrico", (-1132), (-1132), (-1132), (-1132), (Coordinate) null, true, (-1132), linkedList0);
      CarroEletrico carroEletrico1 = carroEletrico0.clone();
      assertTrue(carroEletrico1.getDisponibilidade());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      CarroEletrico carroEletrico0 = new CarroEletrico();
      CarroEletrico carroEletrico1 = new CarroEletrico(carroEletrico0);
      boolean boolean0 = carroEletrico0.equals(carroEletrico1);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      CarroEletrico carroEletrico0 = new CarroEletrico();
      String string0 = carroEletrico0.toString();
      assertEquals("***** Carro El\u00E9trico *****\n*****    VE\u00CDCULO    *****\nMarca: \nMatr\u00EDcula: \nNIF do Propriet\u00E1rio: \nVelocidade M\u00E9dia: 0\nPre\u00E7o Base por Km: 0.0\nConsumo: 0.0\nAutonomia: 0\nPosi\u00E7\u00E3o (latitude e longitude): 0, 0\nDispon\u00EDvel: false\nClassifica\u00E7\u00E3o: 0\n", string0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Coordinate coordinate0 = new Coordinate(0.0, 0.0);
      LinkedList<ParDatas> linkedList0 = new LinkedList<ParDatas>();
      CarroEletrico carroEletrico0 = new CarroEletrico("", (String) null, (String) null, 0, 0, 0, 0, coordinate0, false, 0, linkedList0);
      CarroEletrico carroEletrico1 = new CarroEletrico(carroEletrico0);
      // Undeclared exception!
      try { 
        carroEletrico0.equals(carroEletrico1);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Veiculo", e);
      }
  }
}
