/*
 * This file was automatically generated by EvoSuite
 * Sat Jan 18 19:40:40 GMT 2020
 */


import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.LinkedList;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class CarroHibrido_ESTest extends CarroHibrido_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Coordinate coordinate0 = new Coordinate(0.0, 0.0);
      LinkedList<ParDatas> linkedList0 = new LinkedList<ParDatas>();
      CarroHibrido carroHibrido0 = new CarroHibrido("fNE4", "~bP!`O(T?{)(%8,", "~bP!`O(T?{)(%8,", 0, 1142.0, 655.4471683, 0, coordinate0, true, 0, linkedList0);
      CarroHibrido carroHibrido1 = carroHibrido0.clone();
      assertEquals("fNE4", carroHibrido1.getMarca());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      CarroHibrido carroHibrido0 = new CarroHibrido();
      carroHibrido0.setClassificacao(6424);
      CarroHibrido carroHibrido1 = carroHibrido0.clone();
      assertEquals("", carroHibrido1.getMarca());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Coordinate coordinate0 = new Coordinate((-1074.570023341302), (-1074.570023341302));
      LinkedList<ParDatas> linkedList0 = new LinkedList<ParDatas>();
      CarroHibrido carroHibrido0 = new CarroHibrido("6sb#?", "6sb#?", "", 1063, 1063, (-1472.7355267635), 1063, coordinate0, true, 0, linkedList0);
      CarroHibrido carroHibrido1 = carroHibrido0.clone();
      assertEquals(1063.0, carroHibrido1.getPreco(), 0.01);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Coordinate coordinate0 = new Coordinate((-1.0), 518.011457022);
      CarroHibrido carroHibrido0 = new CarroHibrido();
      List<ParDatas> list0 = carroHibrido0.getDatasAlugueres();
      CarroHibrido carroHibrido1 = new CarroHibrido("", "", "Weather", (-922), (-922), (-922), (-922), coordinate0, true, (-1), list0);
      CarroHibrido carroHibrido2 = carroHibrido1.clone();
      assertNotSame(carroHibrido0, carroHibrido2);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      CarroHibrido carroHibrido0 = new CarroHibrido();
      carroHibrido0.setPosicao((Coordinate) null);
      // Undeclared exception!
      try { 
        carroHibrido0.toString();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Veiculo", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Coordinate coordinate0 = new Coordinate(1583, (-332.8185));
      CarroHibrido carroHibrido0 = new CarroHibrido();
      List<ParDatas> list0 = carroHibrido0.getDatasAlugueres();
      CarroHibrido carroHibrido1 = new CarroHibrido("", "", "", 1583, 215.32231506088, 1583, 1583, coordinate0, false, (-1131), list0);
      carroHibrido0.setMarca((String) null);
      // Undeclared exception!
      try { 
        carroHibrido0.equals(carroHibrido1);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Veiculo", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Coordinate coordinate0 = new Coordinate((-205.89034385486), (-867.2835075736));
      LinkedList<ParDatas> linkedList0 = new LinkedList<ParDatas>();
      linkedList0.add((ParDatas) null);
      CarroHibrido carroHibrido0 = null;
      try {
        carroHibrido0 = new CarroHibrido("", "", "", 875, 875, (-867.2835075736), 875, coordinate0, false, 0, linkedList0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.stream.ReferencePipeline$3$1", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      CarroHibrido carroHibrido0 = new CarroHibrido();
      CarroHibrido carroHibrido1 = new CarroHibrido(carroHibrido0);
      assertEquals(0.0, carroHibrido1.getConsumo(), 0.01);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      CarroHibrido carroHibrido0 = new CarroHibrido();
      boolean boolean0 = carroHibrido0.equals((Object) null);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      CarroHibrido carroHibrido0 = new CarroHibrido();
      boolean boolean0 = carroHibrido0.equals(carroHibrido0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      CarroHibrido carroHibrido0 = new CarroHibrido();
      boolean boolean0 = carroHibrido0.equals("***** Carro H\u00EDbrido *****\n*****    VE\u00CDCULO    *****\nMarca: \nMatr\u00EDcula: \nNIF do Propriet\u00E1rio: \nVelocidade M\u00E9dia: 1583\nPre\u00E7o Base por Km: 215.32231506088\nConsumo: 1583.0\nAutonomia: 1583\nPosi\u00E7\u00E3o (latitude e longitude): 1583, 0\nDispon\u00EDvel: false\nClassifica\u00E7\u00E3o: -1131\n");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      CarroHibrido carroHibrido0 = new CarroHibrido();
      String string0 = carroHibrido0.toString();
      assertEquals("***** Carro H\u00EDbrido *****\n*****    VE\u00CDCULO    *****\nMarca: \nMatr\u00EDcula: \nNIF do Propriet\u00E1rio: \nVelocidade M\u00E9dia: 0\nPre\u00E7o Base por Km: 0.0\nConsumo: 0.0\nAutonomia: 0\nPosi\u00E7\u00E3o (latitude e longitude): 0, 0\nDispon\u00EDvel: false\nClassifica\u00E7\u00E3o: 0\n", string0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      CarroHibrido carroHibrido0 = null;
      try {
        carroHibrido0 = new CarroHibrido((CarroHibrido) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Veiculo", e);
      }
  }
}
