/*
 * This file was automatically generated by EvoSuite
 * Sat Jan 18 19:42:26 GMT 2020
 */


import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.LinkedList;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ComparadorPreco_ESTest extends ComparadorPreco_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ComparadorPreco comparadorPreco0 = new ComparadorPreco();
      Veiculo veiculo0 = new Veiculo();
      List<ParDatas> list0 = veiculo0.getDatasAlugueres();
      Veiculo veiculo1 = new Veiculo("g*fW", "vUxe", "hYCqq,9nv[1eV0Pc{RM", (-1026), (-1026), (-1.0), (-1026), (Coordinate) null, false, (-1326), list0);
      int int0 = comparadorPreco0.compare(veiculo1, veiculo0);
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ComparadorPreco comparadorPreco0 = new ComparadorPreco();
      Veiculo veiculo0 = new Veiculo();
      // Undeclared exception!
      try { 
        comparadorPreco0.compare(veiculo0, (Veiculo) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("ComparadorPreco", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      ComparadorPreco comparadorPreco0 = new ComparadorPreco();
      Coordinate coordinate0 = new Coordinate(1, 1);
      LinkedList<ParDatas> linkedList0 = new LinkedList<ParDatas>();
      Veiculo veiculo0 = new Veiculo((String) null, (String) null, (String) null, 1, 1, 1, 1, coordinate0, true, 1, linkedList0);
      Veiculo veiculo1 = new Veiculo();
      int int0 = comparadorPreco0.compare(veiculo0, veiculo1);
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      ComparadorPreco comparadorPreco0 = new ComparadorPreco();
      Coordinate coordinate0 = new Coordinate(1, 1);
      LinkedList<ParDatas> linkedList0 = new LinkedList<ParDatas>();
      Veiculo veiculo0 = new Veiculo((String) null, (String) null, (String) null, 1, 1, 1, 1, coordinate0, true, 1, linkedList0);
      int int0 = comparadorPreco0.compare(veiculo0, veiculo0);
      assertEquals((-1), int0);
  }
}
