/*
 * This file was automatically generated by EvoSuite
 * Sat Jan 18 19:43:29 GMT 2020
 */


import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.LinkedList;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ComparadorAutonomia_ESTest extends ComparadorAutonomia_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ComparadorAutonomia comparadorAutonomia0 = new ComparadorAutonomia();
      LinkedList<ParDatas> linkedList0 = new LinkedList<ParDatas>();
      Veiculo veiculo0 = new Veiculo("}tp;f9sB", "}tp;f9sB", "}tp;f9sB", (-16), (-16), (-16), (-16), (Coordinate) null, false, (-16), linkedList0);
      Veiculo veiculo1 = new Veiculo();
      int int0 = comparadorAutonomia0.compare(veiculo0, veiculo1);
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ComparadorAutonomia comparadorAutonomia0 = new ComparadorAutonomia();
      Coordinate coordinate0 = new Coordinate(446.184012, (-268));
      LinkedList<ParDatas> linkedList0 = new LinkedList<ParDatas>();
      Veiculo veiculo0 = new Veiculo("ComparadorAutonomia", (String) null, "ComparadorAutonomia", (-268), (-1.772754228251), 947.772, (-268), coordinate0, true, 0, linkedList0);
      // Undeclared exception!
      try { 
        comparadorAutonomia0.compare((Veiculo) null, veiculo0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("ComparadorAutonomia", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      ComparadorAutonomia comparadorAutonomia0 = new ComparadorAutonomia();
      LinkedList<ParDatas> linkedList0 = new LinkedList<ParDatas>();
      Veiculo veiculo0 = new Veiculo("}tp;f9sB", "}tp;f9sB", "}tp;f9sB", (-16), (-16), (-16), (-16), (Coordinate) null, false, (-16), linkedList0);
      Veiculo veiculo1 = new Veiculo();
      int int0 = comparadorAutonomia0.compare(veiculo1, veiculo0);
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      ComparadorAutonomia comparadorAutonomia0 = new ComparadorAutonomia();
      LinkedList<ParDatas> linkedList0 = new LinkedList<ParDatas>();
      Veiculo veiculo0 = new Veiculo("}tp;f9sB", "}tp;f9sB", "}tp;f9sB", (-16), (-16), (-16), (-16), (Coordinate) null, false, (-16), linkedList0);
      int int0 = comparadorAutonomia0.compare(veiculo0, veiculo0);
      assertEquals((-1), int0);
  }
}
