/*
 * This file was automatically generated by EvoSuite
 * Sat Jan 18 19:43:21 GMT 2020
 */


import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.util.MockGregorianCalendar;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ComparadorKm_ESTest extends ComparadorKm_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ComparadorKm comparadorKm0 = new ComparadorKm();
      MockGregorianCalendar mockGregorianCalendar0 = new MockGregorianCalendar();
      Coordinate coordinate0 = new Coordinate(0.0, 49.959);
      Cliente cliente0 = new Cliente("%|&18t/0\"PdY", "", "5LUh*kl>z35", "/", "", mockGregorianCalendar0, coordinate0, 0, 0, 6134.74);
      Cliente cliente1 = new Cliente();
      int int0 = comparadorKm0.compare(cliente0, cliente1);
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Cliente cliente0 = new Cliente();
      ComparadorKm comparadorKm0 = new ComparadorKm();
      Cliente cliente1 = new Cliente();
      cliente1.setNKM((-1));
      int int0 = comparadorKm0.compare(cliente1, cliente0);
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Cliente cliente0 = new Cliente();
      ComparadorKm comparadorKm0 = new ComparadorKm();
      int int0 = comparadorKm0.compare(cliente0, cliente0);
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      ComparadorKm comparadorKm0 = new ComparadorKm();
      // Undeclared exception!
      try { 
        comparadorKm0.compare((Cliente) null, (Cliente) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("ComparadorKm", e);
      }
  }
}
