/*
 * This file was automatically generated by EvoSuite
 * Sat Jan 18 19:36:12 GMT 2020
 */


import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.NoSuchElementException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.util.SystemInUtil;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Menu_ESTest extends Menu_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      String[] stringArray0 = new String[1];
      stringArray0[0] = "1";
      SystemInUtil.addInputLine("1");
      Menu menu0 = new Menu(stringArray0);
      assertEquals(0, menu0.getOpcao());
      
      menu0.executa();
      assertEquals(1, menu0.getOpcao());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      SystemInUtil.addInputLine("0 - Sair\n ");
      String[] stringArray0 = new String[5];
      stringArray0[0] = "0 - Sair\n ";
      Menu menu0 = new Menu(stringArray0);
      menu0.executa();
      assertEquals(0, menu0.getOpcao());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      SystemInUtil.addInputLine("0 - Sair\n ");
      // Undeclared exception!
      try { 
        Menu.MenuLerInt(10, (-3500), "=l3^W0l!q+{N`Rw>/II", "");
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      SystemInUtil.addInputLine("1");
      int int0 = Menu.MenuLerInt(1, 1, "1", "'LoX~=hKmJD}");
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      SystemInUtil.addInputLine("0 - Sair\n ");
      int int0 = Menu.MenuLerInt((-24), 806, "", "c4kB=wJ=j)aB$");
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      String[] stringArray0 = new String[7];
      Menu menu0 = new Menu(stringArray0);
      // Undeclared exception!
      try { 
        menu0.executa();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Menu", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      String[] stringArray0 = new String[0];
      Menu menu0 = new Menu(stringArray0);
      // Undeclared exception!
      try { 
        menu0.executa();
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 0
         //
         verifyException("java.util.Arrays$ArrayList", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Menu menu0 = null;
      try {
        menu0 = new Menu((String[]) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Objects", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      SystemInUtil.addInputLine("\n **** ");
      String[] stringArray0 = new String[2];
      stringArray0[0] = "\n **** ";
      Menu menu0 = new Menu(stringArray0);
      // Undeclared exception!
      try { 
        menu0.executa();
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      SystemInUtil.addInputLine("0 - a+i+VY6HAV");
      // Undeclared exception!
      try { 
        Menu.MenuLerInt((-3276), (-3276), "0 - a+i+VY6HAV", "0 - a+i+VY6HAV");
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      String[] stringArray0 = new String[2];
      stringArray0[0] = "1";
      SystemInUtil.addInputLine("1");
      Menu menu0 = new Menu(stringArray0);
      assertEquals(0, menu0.getOpcao());
      
      menu0.executa();
      int int0 = menu0.getOpcao();
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      SystemInUtil.addInputLine("+5");
      String[] stringArray0 = new String[1];
      stringArray0[0] = "+5";
      Menu menu0 = new Menu(stringArray0);
      // Undeclared exception!
      try { 
        menu0.executa();
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      String[] stringArray0 = new String[2];
      Menu menu0 = new Menu(stringArray0);
      int int0 = menu0.getOpcao();
      assertEquals(0, int0);
  }
}
